inputs:
  path: /home/rebecca/cernbox/O_O/MC
  production: LHC25i4
  prefixGen: AnalysisResults_dq_efficiency_with_assoc # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults]
  prefixRec: AnalysisResults_dq_efficiency_with_assoc # [AnalysisResults_dq_efficiency_with_assoc, AnalysisResults]
  assocType: std_association
  sigGen: Jpsi
  sigRec: mumuFromJpsi
  cuts: [matchedMchMid]
  hlistGen: analysis-same-event-pairing/output
  listGen: MCTruthGenSel
  #histGen: Pt_Rapidity # dq-efficiency
  histGen: PtMC_YMC # dq-efficiency-with-assoc
  hlistRec: analysis-same-event-pairing/output
  listRec: PairsMuonSEPM
  histRec: Mass_Pt_centrFT0C_V2
  # Integrated Pt and Rap bins for THn, TH2 projections
  # Keep the same limits also in the differential bins!
  minPtBinInt: 0.0
  maxPtBinInt: 20.0
  minRapBinInt: 2.50
  maxRapBinInt: 4.00
  #ptBins: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0]
  #rapBins: [2.50, 4.00]
  ptBins: [0.0, 20.0]
  rapBins: [2.50, 4.00]

scan:
  path: /Users/lucamicheletti/cernbox/JPSI/Jpsi_pp_ref_cross_section_run3/MC/LHC25g9/Runs
  runList: run_list.txt
  fileName: axe_pt_dependence_std_association_Jpsi

outputs:
  path: data/MC
  prefix: axe_integrated # [integrated, pt_dependence, rap_dependence]